### ISSUE TITLE
RA and Dec should be allowed to be set to nonnull

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/healpix-alchemy#13]
Currently the RA and Dec columns in `Point` are allowed to be null. It's good to have this option, but it forces subclasses that inherit from `Point` to have nullable RA and Dec columns. In skyportal, our API validators and schema documentation are autogenerated off the SQLa model, so we need to be able to sometimes have RA and Dec be nonnull (and sometimes null). Is there a way we can make this configurable at the healpix alchemy level ?

**Comment by dannygoldstein** [comment]
Specifically, say I have a photometry class that inherits Point. I want its Ra and Dec columns to be nullable. Then I have an Obj class that inherits Point,  but I need its RA and Dec columns to be nonnull.

**Comment by lpsinger** [comment]
@mcoughlin, it turns out that these columns were nullable quite by accident. However, that seems to be what you need. Do you need a non-nullable version too?

**Comment by mcoughlin** [comment]
@stefanv should answer this, as I expect he understands this intuitively. Maybe this choice is too far gone at this point?

**Comment by lpsinger** [comment]
Won't fix.
