### ISSUE TITLE
Check computational complexity of PostgreSQL 14 multiranges

### ISSUE THREAD

**Issue by lpsinger** [skyportal/healpix-alchemy#22]
PostreSQL 14 multiranges are a promising solution for #18. Experimentally verify the computational complexity of the following functions and operations introduced in PostgreSQL 13:

1. [ ] `range_agg` over _N_ rows of an `INT8RANGE` column with a `GIST` index: _O(N)_
2. [ ] take result of `range_agg` from query 1, find intersection with _M_ rows of an `INT8` column with a `GIST` index: _O((N + M) log (N + M))_
3. [ ] take result of `range_agg` from query 1, find intersection with _M_ rows of an `INT8RANGE` column with a `GIST` index: _O((N + M) log (N + M))_

**Comment by bparazin** [comment]
Also, since the && is between ranges/multiranges, do you want it done on a row by row basis, or apply some kind of aggregate? So if the final multirange is {(3, 5), (8,10)} for example, and the table column is (4,10),(6,7), (3,11) do you want it to return t or t, f, t? Sorry for all the questions, I want to make sure I'm doing this correctly

**Comment by lpsinger** [comment]
> Looking at [this](https://www.postgresql.org/docs/current/functions-range.html), it looks like && is only good for comparing ranges & multiranges? Is there an additional extension I should install to use it with `int8` (or am I just reading this wrong)?

I'm sorry, you're right. For scalars, the operator to test is:

anymultirange @> anyelement → boolean

**Comment by bparazin** [comment]
![image](https://user-images.githubusercontent.com/56836732/137043774-3ee31c06-7250-4d23-a100-8fb52ad0d131.png)
![image](https://user-images.githubusercontent.com/56836732/137043796-55fb58b5-a043-4614-a32b-befce4427364.png)
Yeah, I didn't run for as high M this time just for time, but both seem pretty credible. Let me run a larger step size and higher upper bound tonight & I'll post the results of that tomorrow morning
