### ISSUE TITLE
pytest fails, distutils is deprecated

### ISSUE THREAD

**Issue by Tohuvavohu** [skyportal/healpix-alchemy#48]
Running the steps according to the instructions in README, pytest interrupts itself and errors out, saying:

> E   DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

This error is the same regardless of whether I install the venv using Poetry with python 3.7, 3.8 or 3.9 and prevents running the test suite.

**Comment by lpsinger** [comment]
I can't reproduce. Can you post your full terminal session, including the command that you used to run the tests, and all of the output?

**Comment by Tohuvavohu** [comment]
`<pre><font color="#8AE234"><b>aaron@hardthinker</b></font>:<font color="#729FCF"><b>~</b></font>$ curl -sSL https://install.python-poetry.org | python3.9 -
<font color="#06989A">Retrieving Poetry metadata</font>

# Welcome to <font color="#06989A">Poetry</font>!

This will download and install the latest version of <font color="#06989A">Poetry</font>,
a dependency and package manager for Python.

It will add the `poetry` command to <font color="#06989A">Poetry</font>&apos;s bin directory, located at:

<font color="#C4A000">/home/aaron/.local/bin</font>

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing <font color="#06989A">Poetry</font> (<b>1.1.13</b>): <font color="#C4A000">Done</font>

<font color="#06989A">Poetry</font> (<b>1.1.13</b>) is installed now. Great!

You can test that everything is set up by executing:

`<b>poetry --version</b>`

<font color="#8AE234"><b>aaron@hardthinker</b></font>:<font color="#729FCF"><b>~</b></font>$ poetry --version
Poetry version <font color="#06989A">1.1.13</font>
<font color="#8AE234"><b>aaron@hardthinker</b></font>:<font color="#729FCF"><b>~</b></font>$ git clone git@github.com:skyportal/healpix-alchemy.git
Cloning into &apos;healpix-alchemy&apos;...
remote: Enumerating objects: 613, done.
remote: Counting objects: 100% (125/125), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 613 (delta 83), reused 71 (delta 71), pack-reused 488
Receiving objects: 100% (613/613), 221.76 KiB | 2.88 MiB/s, done.
Resolving deltas: 100% (356/356), done.
<font color="#8AE234"><b>aaron@hardthinker</b></font>:<font color="#729FCF"><b>~</b></font>$ cd healpix-alchemy/
<font color="#8AE234"><b>aaron@hardthinker</b></font>:<font color="#729FCF"><b>~/healpix-alchemy</b></font>$ poetry install
<font color="#3465A4">Installing dependencies from lock file</font>

No dependencies to install or update

<b>Installing</b> the current project: <font color="#06989A">healpix-alchemy</font> (<font color="#4E9A06">1.0.1</font>)
<font color="#8AE234"><b>aaron@hardthinker</b></font>:<font color="#729FCF"><b>~/healpix-alchemy</b></font>$ poetry shell
Spawning shell within <font color="#3465A4">/home/aaron/.cache/pypoetry/virtualenvs/healpix-alchemy-Uzg-A8By-py3.9</font>
. /home/aaron/.cache/pypoetry/virtualenvs/healpix-alchemy-Uzg-A8By-py3.9/bin/activate
<font color="#8AE234"><b>aaron@hardthinker</b></font>:<font color="#729FCF"><b>~/healpix-alchemy</b></font>$ . /home/aaron/.cache/pypoetry/virtualenvs/healpix-alchemy-Uzg-A8By-py3.9/bin/activate
(healpix-alchemy-Uzg-A8By-py3.9) <font color="#8AE234"><b>aaron@hardthinker</b></font>:<font color="#729FCF"><b>~/healpix-alchemy</b></font>$ pytest
<b>=================================== test session starts ===================================</b>
platform linux -- Python 3.9.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/aaron/healpix-alchemy, configfile: pyproject.toml
plugins: doctestplus-0.11.2, postgresql-3.1.2, benchmark-3.4.1
<b>collected 0 items / 1 error                                                               </b>

========================================= ERRORS ==========================================
<font color="#EF2929"><b>______________________________ ERROR collecting test session ______________________________</b></font>
<font color="#EF2929"><b>/usr/lib/python3.9/importlib/__init__.py</b></font>:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:1030: in _gcd_import
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:1007: in _find_and_load
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:972: in _find_and_load_unlocked
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:228: in _call_with_frames_removed
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:1030: in _gcd_import
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:1007: in _find_and_load
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:972: in _find_and_load_unlocked
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:228: in _call_with_frames_removed
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:1030: in _gcd_import
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:1007: in _find_and_load
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:972: in _find_and_load_unlocked
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:228: in _call_with_frames_removed
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:1030: in _gcd_import
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:1007: in _find_and_load
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:986: in _find_and_load_unlocked
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:680: in _load_unlocked
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap_external&gt;</b></font>:850: in exec_module
    ???
<font color="#EF2929"><b>&lt;frozen importlib._bootstrap&gt;</b></font>:228: in _call_with_frames_removed
    ???
<font color="#EF2929"><b>healpix_alchemy/__init__.py</b></font>:1: in &lt;module&gt;
    from .types import Point, Tile
<font color="#EF2929"><b>healpix_alchemy/types.py</b></font>:5: in &lt;module&gt;
    from astropy.coordinates import SkyCoord
<font color="#EF2929"><b>../.cache/pypoetry/virtualenvs/healpix-alchemy-Uzg-A8By-py3.9/lib/python3.9/site-packages/astropy/__init__.py</b></font>:42: in &lt;module&gt;
    from . import config as _config  # noqa: E402
<font color="#EF2929"><b>../.cache/pypoetry/virtualenvs/healpix-alchemy-Uzg-A8By-py3.9/lib/python3.9/site-packages/astropy/config/__init__.py</b></font>:10: in &lt;module&gt;
    from .configuration import *
<font color="#EF2929"><b>../.cache/pypoetry/virtualenvs/healpix-alchemy-Uzg-A8By-py3.9/lib/python3.9/site-packages/astropy/config/configuration.py</b></font>:26: in &lt;module&gt;
    from astropy.utils.compat.context import nullcontext
<font color="#EF2929"><b>../.cache/pypoetry/virtualenvs/healpix-alchemy-Uzg-A8By-py3.9/lib/python3.9/site-packages/astropy/utils/compat/__init__.py</b></font>:19: in &lt;module&gt;
    from .numpycompat import *  # noqa
<font color="#EF2929"><b>../.cache/pypoetry/virtualenvs/healpix-alchemy-Uzg-A8By-py3.9/lib/python3.9/site-packages/astropy/utils/compat/numpycompat.py</b></font>:13: in &lt;module&gt;
    NUMPY_LT_1_18 = not minversion(&apos;numpy&apos;, &apos;1.18&apos;)
<font color="#EF2929"><b>../.cache/pypoetry/virtualenvs/healpix-alchemy-Uzg-A8By-py3.9/lib/python3.9/site-packages/astropy/utils/introspection.py</b></font>:160: in minversion
    return LooseVersion(have_version) &gt;= LooseVersion(version)
<font color="#EF2929"><b>../.cache/pypoetry/virtualenvs/healpix-alchemy-Uzg-A8By-py3.9/lib/python3.9/site-packages/setuptools/_distutils/version.py</b></font>:53: in __init__
    warnings.warn(
<font color="#EF2929"><b>E   DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.</b></font>
================================= short test summary info =================================
ERROR  - DeprecationWarning: distutils Version classes are deprecated. Use packaging.ver...
!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!
<font color="#CC0000">==================================== </font><font color="#EF2929"><b>1 error</b></font><font color="#CC0000"> in 0.42s =====================================</font></pre>`

**Comment by lpsinger** [comment]
Ah, I can reproduce this in Python 3.9. If you're in a hurry, give Python 3.8 a shot while I debug this.

**Comment by Tohuvavohu** [comment]
Leo, thanks :)
Actually 

> This error is the same regardless of whether I install the venv using Poetry with python 3.7, 3.8 or 3.9....
The command  sequence was identical, just changing python 3.9 to 3.8 and 3.7 in the poetry install (after subsequent uninstall)

**Comment by lpsinger** [comment]
Interesting. Try #49 though. It seems to fix it for me.

**Comment by Tohuvavohu** [comment]
works now, thanks Leo!
